function [image,filteredImage] = meanFilter(image, matrixSize)
% @author: Mehmet KIRAN
% @date: 21.11.2018
% @license: GNU GPL v3
% How To Use
% This function requires two parameters. 
% The first parameter is the image path, the second parameter is the matrix size.

image = imread(image);
[x, y, z] =size(image);
mI = image;
I = image;

%3x3 Mean Filter
if matrixSize == 3
for i1 = 2:x-1
    for i2=2:y-1
        for i3 =1:z
            m =             ( [I(i1-1, i2-1, i3)./ 8 ...
                             + I(i1, i2-1, i3)./  8 ...
                             + I(i1+1, i2-1, i3) ./  8 ...
                             + I(i1-1, i2, i3) ./  8 ...
                             + I(i1, i2, i3)./ 8 ...
                             + I(i1+1, i2, i3)./ 8 ...
                             + I(i1-1, i2+1, i3)./ 8 ...
                             + I(i1, i2+1, i3)./  8 ...
                             + I(i1+1, i2+1, i3)./ 8]);

        mI(i1, i2, i3) = (m);
        end
    end
end
elseif matrixSize == 5 
for i1 = 3:x-2
    for i2=3:y-2
        for i3 =1:z
            m =             ( [I(i1-2, i2-1, i3) ./ 24 ...
                             I(i1-1, i2-1, i3) ./ 24 ...
                             I(i1  , i2-1, i3) ./ 24 ...
                             I(i1+1, i2-1, i3) ./ 24 ...
                             I(i1+2, i2-1, i3) ./ 24 ...
                             I(i1-2, i2, i3) ./ 24 ...
                             I(i1-1, i2, i3) ./ 24 ...
                             I(i1  , i2, i3) ./ 24 ...
                             I(i1+1, i2, i3) ./ 24 ...
                             I(i1+2, i2, i3),...
                             I(i1-2, i2+1, i3) ./ 24 ...
                             I(i1-1, i2+1, i3) ./ 24 ...
                             I(i1  , i2+1, i3) ./ 24 ...
                             I(i1+1, i2+1, i3) ./ 24 ...
                             I(i1+2, i2+1, i3)./ 24]);

        mI(i1, i2, i3) = (m);
        end
    end
end

else
    disp('Invalid value entered / Gecersiz Deger Girildi');
end    
    
filteredImage = mI;
subplot(1,2,1);
imshow(image);
subplot(1,2,2);
imshow(filteredImage);


 
end
